# Generated by Django 2.2.7 on 2019-12-26 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191226_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 4, 18, 36, 978681, tzinfo=utc)),
        ),
    ]
